# Generated by Django 5.0.1 on 2024-01-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0002_contact_info_alter_blog_category_blog_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='u_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='u_message',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
