# Generated by Django 5.0.1 on 2024-01-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0003_alter_contact_info_u_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
