# Generated by Django 5.0.1 on 2024-01-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0004_email_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_info',
            name='userEmail',
            field=models.EmailField(max_length=254),
        ),
    ]
