# Generated by Django 5.0.1 on 2024-01-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0005_alter_email_info_useremail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_info',
            old_name='userEmail',
            new_name='UserSub',
        ),
    ]
