# Generated by Django 5.0.1 on 2024-01-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0006_rename_useremail_email_info_usersub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_info',
            old_name='UserSub',
            new_name='user_email2',
        ),
    ]
