# Generated by Django 5.0.1 on 2024-01-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0007_rename_usersub_email_info_user_email2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_info',
            old_name='user_email2',
            new_name='Email_Id',
        ),
    ]
