# Generated by Django 5.0.1 on 2024-01-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0008_rename_user_email2_email_info_email_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='email_info',
        ),
    ]
