# Generated by Django 5.0.1 on 2024-01-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0009_delete_email_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='u_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='u_message',
            field=models.CharField(max_length=200),
        ),
    ]
