# Generated by Django 5.0.1 on 2024-01-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0011_blog_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_post',
            new_name='blog_posts',
        ),
    ]
