# Generated by Django 5.0.1 on 2024-01-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0013_blog_posts_blog_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_posts',
            old_name='blog_cat',
            new_name='blog_cat_post',
        ),
    ]
