# Generated by Django 5.0.1 on 2024-01-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0018_alter_blog_posts_blog_cat_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_posts',
            name='blog_cat_post',
        ),
    ]
