# Generated by Django 5.0.1 on 2024-02-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0020_blog_posts_blog_cat_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_posts',
            name='like_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='blog_posts',
            name='views_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
