# Generated by Django 5.0.1 on 2024-02-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0021_blog_posts_like_count_blog_posts_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_info', models.CharField(max_length=100)),
                ('comment_email', models.EmailField(max_length=100)),
                ('comment_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myblogs.blog_posts')),
            ],
        ),
    ]
