# Generated by Django 5.0.1 on 2024-02-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0023_alter_comment_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
    ]
