# Generated by Django 5.0.1 on 2024-02-05 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0025_comment_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myblogs.blog_posts'),
        ),
    ]
