# Generated by Django 5.0.1 on 2024-02-06 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogs', '0026_comment_comment_email_alter_comment_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_posts',
            old_name='blog_cat_post',
            new_name='blog_cat',
        ),
    ]
